- hosts: all
  tasks:
  - name: Install the latest Apache Version
    yum: 
      name: httpd
      state: latest
    become: yes
    become_user: root
    become_method: su
    become_password: Sn0wComm@nder!
    notify:
    - startservice
  handlers:
  - name: startservice
    service:
      name: httpd
      state: restarted
